basePath: /
consumes:
    - application/json
definitions: {}
info:
    title: restapi
    version: 1.0.0
    license:
        name: ISC
    contact: {}
paths:
    /addOrder/create:
        post:
            operationId: AddNewOrder
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            consumes:
                - application/json
            description: 'Create a new order'
            security: []
            parameters:
                -
                    in: body
                    name: res
                    required: true
                    schema:
                        type: object
    /addOrder/all:
        get:
            operationId: GetOrders
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            description: 'Get all orders'
            security: []
            parameters: []
    /addOrder/details:
        post:
            operationId: GetOrderDetails
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            consumes:
                - application/json
            description: 'Get details from order'
            security: []
            parameters:
                -
                    in: body
                    name: res
                    required: true
                    schema:
                        type: object
    /products/all:
        get:
            operationId: GetProducts
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            description: 'Get all Products'
            security: []
            parameters: []
    /products/create:
        post:
            operationId: Create
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            consumes:
                - application/json
            description: 'Create a new product'
            security: []
            parameters:
                -
                    in: body
                    name: res
                    required: true
                    schema:
                        type: object
    /products/byType:
        post:
            operationId: ByType
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            consumes:
                - application/json
            description: 'Show product by type'
            summary: 'A concise summary.'
            security: []
            parameters:
                -
                    in: body
                    name: res
                    required: true
                    schema:
                        type: object
    /productsType/create:
        post:
            operationId: Create
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            consumes:
                - application/json
            description: 'Create a type of products'
            summary: 'A concise summary.'
            security: []
            parameters:
                -
                    in: body
                    name: res
                    required: true
                    schema:
                        type: object
    /productsType/all:
        get:
            operationId: GetAll
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            description: 'Get all types of products'
            summary: 'A concise summary.'
            security: []
            parameters: []
    /user:
        get:
            operationId: GetUser
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            security: []
            parameters: []
    /user/login:
        post:
            operationId: LogIn
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            consumes:
                - application/json
            description: 'Login a user'
            security: []
            parameters:
                -
                    in: body
                    name: res
                    required: true
                    schema:
                        type: object
    /user/signin:
        post:
            operationId: SignIn
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            consumes:
                - application/json
            description: 'Create a user'
            summary: y.
            security: []
            parameters:
                -
                    in: body
                    name: res
                    required: true
                    schema:
                        type: object
    /user/signOut:
        post:
            operationId: SignOut
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            consumes:
                - application/json
            description: 'Logout a user'
            security: []
            parameters:
                -
                    in: body
                    name: res
                    required: true
                    schema:
                        type: object
    /user/addFavorites:
        post:
            operationId: AddFavorites
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            consumes:
                - application/json
            description: 'Add a product to fuser favorites'
            summary: 'A concise summary.'
            security: []
            parameters:
                -
                    in: body
                    name: res
                    required: true
                    schema:
                        type: object
    /user/delFavorites:
        delete:
            operationId: DelFavorites
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            consumes:
                - application/json
            description: 'Delete a product from user favorites'
            security: []
            parameters:
                -
                    in: body
                    name: res
                    required: true
                    schema:
                        type: object
    /user/allFavorites:
        get:
            operationId: GetAllFavorites
            produces:
                - application/json
            responses:
                '200':
                    description: Ok
                    schema:
                        additionalProperties: true
            description: 'Get all the favorites from a user'
            security: []
            parameters: []
produces:
    - application/json
swagger: '2.0'
securityDefinitions:
    api_key:
        type: apiKey
        name: access_token
        in: query
    tsoa_auth:
        type: oauth2
        authorizationUrl: 'http://swagger.io/api/oauth/dialog'
        flow: implicit
        scopes:
            'write:pets': 'modify things'
            'read:pets': 'read things'
